### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by AsamiDolphy** [AsamiDolphy/furima-40223#20]
# フリマアプリのURL 
https://furima-40223.onrender.com/

## Basic認証のIDとパスワード 
ID: admin
パスワード: furi2222

## 出品者用のメールアドレスとパスワード 
メールアドレス: test01@com
パスワード: furi2222

## 購入者用のメールアドレスとパスワード
メールアドレス: test02@com
パスワード: furi2222

**Comment by mo1015** [comment]
@AsamiDolphy さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安・○○をもっと見る）が、見本アプリと同様の形で出力されること**
商品説明が表示されていません。商品説明が表示される場所に「出品者名」が表示されています。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by AsamiDolphy** [comment]
ご確認いただき、ありがとうございます。

私もご指摘いただいた箇所が気になってはいたのですが、その部分の実装を行なった際は、見本アプリもそのような表示になっていました。
https://gyazo.com/bf6070b510b77886c8734a0118b1a1ba

現在は「説明」となっているようです。
https://gyazo.com/48b0458a19c7b0e1bbf81dd14fedb5cc

また、もともとダウンロードしていた"furima_素材_rails7_2023_11 2"のビューファイルは「商品説明」となっていました。

ひとまず、現在の見本アプリに合わせて「説明」に変更しましたのでご確認ください。

**Comment by snkw-works** [comment]
@AsamiDolphy さん、修正とご提出ありがとうございます。

#### 商品詳細ページの商品説明について
社内で確認したところ、直近で商品説明欄に関する見本アプリの変更はございませんでした。
該当商品が既に削除されているため推測とはなってしまいますが、「出品者名」も「商品説明」も「test」という同一のテキストで保存していたため、出品者名が商品説明欄に表示されているように見えていた可能性がございます。

こちらに関してご不明点がございましたらご質問くださいませ。
※ただし、こちらでは技術的なご質問にはお答えいたしかねますので、ご質問内容によってはテックコネクトをご案内する場合がございます。

#### 修正のお願い
動作の確認をしたところ、引き続き修正していただきたい箇所がございましたので、以下のご確認をお願いします！

- [ ] **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安・○○をもっと見る）が、見本アプリと同様の形で出力されるよう修正しましょう**
商品説明欄に「説明」というテキストが表示されています。
こちらには、**出品時に保存した商品説明の内容**が表示されるよう修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by AsamiDolphy** [comment]
そういうことでしたか。
今回も「説明」と説明欄に入っているため、そう見えたということですね。
失礼いたしました。

再度修正いたしましたので、ご確認よろしくお願いいたします。

**Comment by mo1015** [comment]
@AsamiDolphy さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、新たに修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **商品一覧ページにて商品情報をクリックすると、該当する商品の商品詳細表示ページへ遷移すること**
商品詳細表示ページではなくエラー画面に遷移してしまいます。

※商品詳細ページへ遷移できないため、前回依頼した点の修正確認ができませんでした。次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by AsamiDolphy** [comment]
お手数をおかけし、申し訳ございません。
再度デプロイし直しましたので、確認をよろしくお願いいたします。

**Comment by snkw-works** [comment]
@AsamiDolphy さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
